<a href="https://colab.research.google.com/github/T2sif/DA_108/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra with NumPy and SciPy

**Tasks:**
1. Create a 3×3 random matrix and compute its inverse using numpy.linalg.inv().
2. Compute the dot product of two randomly generated vectors using numpy.dot().
3. Perform matrix-vector multiplication with NumPy.
4. Solve a system of linear equations using scipy.linalg.solve().
5. Compute the eigenvalues and eigenvectors of a given square matrix.

In [ ]:
import numpy as np
from scipy import linalg

In [ ]:
#Create a 3×3 random matrix
matrix=np.random.randint(1,10,(3,3))
print(matrix)

[[7 2 1]
 [4 3 3]
 [5 3 7]]


In [ ]:
#its inverse
inverse=linalg.inv(matrix)
print(inverse)

[[ 0.21818182 -0.2         0.05454545]
 [-0.23636364  0.8        -0.30909091]
 [-0.05454545 -0.2         0.23636364]]


In [ ]:
#two randomly generated vectors
vector1=np.random.randint(1,10,3)
vector2=np.random.randint(1,10,3)
print(vector1)
print(vector2)


[7 6 5]
[1 1 2]


In [ ]:
#the dot product of two randomly generated vectors
dot_product=np.dot(vector1,vector2)
print(dot_product)


23


In [ ]:
#Perform matrix-vector multiplication
matrix_vector_1=np.dot(vector1,matrix)
print(matrix_vector_1)


[98 47 60]


**solve the linear equation**

2x+y−z=8

−3x−y+2z=−11

−2x+y+2z=−3
​



In [ ]:
from scipy.linalg import solve

In [ ]:
A=np.array([[2,1,-1],[-3,-1,2],[-2,1,2]])
b=np.array([[8],[-11],[-3]])
X=solve(A,b)
print(X)

[[ 2.]
 [ 3.]
 [-1.]]


**Compute the eigenvalues and eigenvectors of a given square matrix.**

In [ ]:
#first  generating a new 3x3 random diagonal metrix
arr=np.random.randint(1,5,3)
diagonal_matrix=np.diag(arr)
print(diagonal_matrix)

[[4 0 0]
 [0 1 0]
 [0 0 3]]


In [ ]:
eg_val, eg_vect = linalg.eig(diagonal_matrix)
print("The Eigenvalues are :")
print(eg_val)
print("The Eigenvectors are :")
print(eg_vect)

The Eigenvalues are :
[4.+0.j 1.+0.j 3.+0.j]
The Eigenvectors are :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


	**observation:**
diagonal matrix with all distinct diagonal elements.
In that case, the standard basis vectors ([1 0 0], [0 1 0], [0 0 1]) are the eigenvectors.